# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenhush" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "d8077456d8fa4397acf9b07fe656f5dbbec1f1a6b53e748e49e46e49fe72912a"
      url "https://github.com/fregie/tokenhush/releases/download/v#{version}/tokenhush_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d362f9e9f56b07d998a765bb65ca8786887572c92dab5af424534ad99bf6ed15"
      url "https://github.com/fregie/tokenhush/releases/download/v#{version}/tokenhush_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "93fa505427ffe1f085542d3a57831b88e41d96c79991da699d1a568a5dcd4387"
      url "https://github.com/fregie/tokenhush/releases/download/v#{version}/tokenhush_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "298f0bb884d75d99732ce3f51f6a94c332542094fb20e6b6b595f45b965bb2ac"
      url "https://github.com/fregie/tokenhush/releases/download/v#{version}/tokenhush_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tokenhush"
  desc "Local gateway that redacts secrets before they reach AI models"
  homepage "https://github.com/fregie/tokenhush"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokenhush"

  # No zap stanza required

  caveats <<~EOS
    tokenhush is not notarized yet. If macOS blocks the first run, clear the
    quarantine attribute:
      xattr -dr com.apple.quarantine "$(which tokenhush)"
  EOS
end
