# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenhush" do
  version "0.7.1"

  on_macos do
    on_arm do
      sha256 "5cbc548b4f21bd59ae8ba5f1f2030b6825e867db203e131984498d6837b9e63f"
      url "https://github.com/fregie/tokenhush/releases/download/v#{version}/tokenhush_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "842d829bdea412d626d560dbcfc9083a79e1befd6f70f487cc0fd0833d978805"
      url "https://github.com/fregie/tokenhush/releases/download/v#{version}/tokenhush_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "18a58db6df0cd5455f70c92020cacdb4d463345b9faf56b4dba16b0a1068b975"
      url "https://github.com/fregie/tokenhush/releases/download/v#{version}/tokenhush_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "74a1a62670f40fe2600d1d2d3dd674c8bfa360662eb3e4585c04bc92559c201a"
      url "https://github.com/fregie/tokenhush/releases/download/v#{version}/tokenhush_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tokenhush"
  desc "Local gateway that redacts secrets before they reach AI models"
  homepage "https://github.com/fregie/tokenhush"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokenhush"

  # No zap stanza required

  caveats <<~EOS
    tokenhush is not notarized yet. If macOS blocks the first run, clear the
    quarantine attribute:
      xattr -dr com.apple.quarantine "$(which tokenhush)"
  EOS
end
