# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenhush" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "0e53c116a58082f251a6d0d4493249a2d3a2b2491eca9c82c2233fa4b26520da"
      url "https://github.com/fregie/tokenhush/releases/download/v#{version}/tokenhush_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f42450d46b62c7a8e0e2d4252f47ed6ee008417dd567caf28f8cbc076a3a6bbd"
      url "https://github.com/fregie/tokenhush/releases/download/v#{version}/tokenhush_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c92d697d3ea7a70fee99c80ddbb9320cf7f7f356e0c8f54600cc83516786f0c1"
      url "https://github.com/fregie/tokenhush/releases/download/v#{version}/tokenhush_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "974964602f958765c58d0fa6aa0ec36e140ce49ea2ee1dba783fe3cccddd6427"
      url "https://github.com/fregie/tokenhush/releases/download/v#{version}/tokenhush_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tokenhush"
  desc "Local gateway that redacts secrets before they reach AI models"
  homepage "https://github.com/fregie/tokenhush"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokenhush"

  # No zap stanza required

  caveats <<~EOS
    tokenhush is not notarized yet. If macOS blocks the first run, clear the
    quarantine attribute:
      xattr -dr com.apple.quarantine "$(which tokenhush)"
  EOS
end
